<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Alegra/APP/Jose De Armas')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/extjs/6.0.0/classic/theme-classic/resources/theme-classic-all.css')
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
            ->prependFile($this->basePath('js/ext-all.js'))
            ->prependFile($this->basePath('js/locale.js'))
            ->prependFile($this->basePath('js/contactlist.js'))
        ?>
    </head>
    <body>
		
		<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
				<div class="navbar-header">
					 
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						 <span class="sr-only"></span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
					</button> <a class="navbar-brand" href="#">Alegra Contacts Handler</a>
				</div>
				
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li >
							<a href="<?= $this->url('alegra', ['action' => 'index',]) ?>">Home</a>
						</li>

					</ul>
			
				</div>
			</nav>
			<div class="jumbotron">
				
				<script type="text/javascript">
				<?php
				if($_GET['lang']=="en"){
				?>
				var l = locale['en']
				<?
				}else{
				?>
				var l = locale['es']
				<?	
					}
				?>
				
				</script>
				
				<div class="container">
					<?= $this->content ?><?= $this->inlineScript() ?>
					<hr>

				</div>
		
			</div>
		
		
		</div>
	</div>
</div>
		

        
    </body>
</html>
